### PR TITLE
Added stuff need to build for windows

### PR DESCRIPTION
**Pull request by roziscoding**

### CODE REVIEW

**Comment by ecrmnn** [comment]
Awesome!

I'm clueless on how to build for Windows, do you really need an installer?

**Comment by roziscoding** [comment]
You don't need it in order to be able to run the final artifact, but you do in order to get fancy start menu icons and stuff;

It's intended for final users, not indispensable, but also not insignificant.
I guess most people would be OK with running a .exe file from a "C:\Downloads\Programs\Minta" folder, but some might think it's overly complicated.

Anyway, it'd be a fanciness 😝

**Comment by ecrmnn** [comment]
Hey @rjmunhoz. Any progress on this?

**Comment by roziscoding** [comment]
I haven't had the time yet; I should be able to get this done tonight, though.

**Comment by ecrmnn** [comment]
Closing this due to inactivity

**Pull request closed without merging**
